version: '3'

services:
  brevets:
    build: ./brevets
    command: python -u flask_brevets.py
    ports:
      - "5001:80"
    volumes:
      - ./calc
    environment:
    - DB_PORT_27017_TCP_ADDR=db
    depends_on:
    - db
      

  db:
    image: mongo:3.0.2

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5000:80  # host:container
    depends_on:
      - brevets
